server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starsofocean?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host:
    port:
    username:
    password:
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.starsofocean.hotel.pojo